create table "public"."test_supabase" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "supabase_test" text
);


alter table "public"."test_supabase" disable row level security;

CREATE UNIQUE INDEX test_supabase_pkey ON public.test_supabase USING btree (id);

alter table "public"."test_supabase" add constraint "test_supabase_pkey" PRIMARY KEY using index "test_supabase_pkey";

grant delete on table "public"."test_supabase" to "anon";

grant insert on table "public"."test_supabase" to "anon";

grant references on table "public"."test_supabase" to "anon";

grant select on table "public"."test_supabase" to "anon";

grant trigger on table "public"."test_supabase" to "anon";

grant truncate on table "public"."test_supabase" to "anon";

grant update on table "public"."test_supabase" to "anon";

grant delete on table "public"."test_supabase" to "authenticated";

grant insert on table "public"."test_supabase" to "authenticated";

grant references on table "public"."test_supabase" to "authenticated";

grant select on table "public"."test_supabase" to "authenticated";

grant trigger on table "public"."test_supabase" to "authenticated";

grant truncate on table "public"."test_supabase" to "authenticated";

grant update on table "public"."test_supabase" to "authenticated";

grant delete on table "public"."test_supabase" to "service_role";

grant insert on table "public"."test_supabase" to "service_role";

grant references on table "public"."test_supabase" to "service_role";

grant select on table "public"."test_supabase" to "service_role";

grant trigger on table "public"."test_supabase" to "service_role";

grant truncate on table "public"."test_supabase" to "service_role";

grant update on table "public"."test_supabase" to "service_role";